org: ibnzterrell
app: timeline-annotator
service: annotator-api

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  timeout: 30
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
custom:
  wsgi:
    app: AnnotatorAPI.app
    pythonBin: python3 # Some systems with Python3 may require this
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**